#! /bin/zsh

cnf_zsh="$(realpath "$(dirname "$0")")"
jt_local="$(realpath "$cnf_zsh/../..")"

sed "s|\$jt_local|$jt_local|g" "$cnf_zsh/zshrc" > "$HOME/.zshrc"


# TODO The tool only needs to be installed, not called.
"$jt_local/jt" jprompt > /dev/null
