bindkey -v
export KEYTIMEOUT=1

# TODO The tool only needs to be installed, not called.
[ ! -f "$jt_local/toolbox/jprompt/jprompt" ] \
    && "$jt_local/jt" jprompt > /dev/null
setopt PROMPT_SUBST
export PROMPT='$($jt_local/toolbox/jprompt/jprompt) %M@%n %5~ %# %E'

export PATH="$PATH:$jt_local"
