# Jonathan Frech's zshrc; last modified 2020-11-04

bindkey -v
export KEYTIMEOUT=1

export EDITOR='vim'
export BROWSER='brave-browser'
export LESSHISTSIZE=0

alias ls='ls --color=auto -A'
alias grep='grep --color=auto'
alias brave='brave --incognito'

setopt PROMPT_SUBST
"$jt_local/jt" internal build zsh-prompt
export PROMPT='$($jt_local/toolbox/zsh-prompt/zsh-prompt)'

export PATH="$PATH:/home/j/.jt"
