#! /bin/zsh

tool_dir="$(realpath "$(dirname "$0")")"
dot_jt="$(realpath "$tool_dir/../..")"
jt="$dot_jt/jt"

"$jt" internal list all | sed 's/^\[.*\] //' | grep '^cnf-' | grep -v '^cnf-all$' | xargs -l "$jt"
