" Jonathan Frech's .vimrc

set number 
set numberwidth=4
set colorcolumn=80

set syntax
colo j

" use four spaces instead of a tab
set expandtab softtabstop=4 shiftwidth=4 shiftround=4

" special characters
set linebreak breakindent &showbreak='~: '
set list listchars=tab:>>,trail:~,nbsp:!
" set listchars=eol:.,space:.

" messages and menus
set shortmess=asTIc
set wildmenu wildmode=longest,full

" by default, splits shall open above and to the left
set splitbelow splitright

" ban arrow keys
nnoremap <Left>  <Nop>
nnoremap <Right> <Nop>
nnoremap <Up>    <Nop>
nnoremap <Down>  <Nop>
inoremap <Left>  <Nop>
inoremap <Right> <Nop>
inoremap <Up>    <Nop>
inoremap <Down>  <Nop>
vnoremap <Left>  <Nop>
vnoremap <Right> <Nop>
vnoremap <Up>    <Nop>
vnoremap <Down>  <Nop>
cnoremap <Left>  <Nop>
cnoremap <Right> <Nop>
cnoremap <Up>    <Nop>
cnoremap <Down>  <Nop>

" relay vim's title
set title
