#! /bin/zsh

# Recursively goes thru a given directory and searches identical files.

jt="$(realpath "$(dirname "$0")/../../jt")"
fail () { "$jt" internal fail $@ ; exit 1 }

hashsum='md5sum'

[ ! "$#" = '1' ] && fail 'No argument given.'
root="$(realpath "$1")"

hash_files=()
handle () {
    hf="$("$hashsum" "$1")"
    h="${hf%% *}" f="${hf#*  }"
    hash_files+=("$h $f")
    printf '# %s "%q"\n' "$h" "$f" }
find "$root" -type f | while read f; do handle "$f"; done

printf '\n'
cat "$(dirname "$0")/identical.zsh.snippet"
printf '\n'

for hf in $hash_files; do
    h="${hf%% *}"
    printf '%s\n' "$h"
done | sort | uniq -d | while read uniq_h; do
    files_of_same_hash=()
    for hf in $hash_files; do
        h="${hf%% *}" f="${hf#* }"
        [ "$uniq_h" = "$h" ] || continue
        files_of_same_hash+=("$f")
    done

    [ "$#files_of_same_hash" -le '1' ] && fail 'Internal catastrophy.'
    first_file="${files_of_same_hash[1]}"
    for fosh in $files_of_same_hash; do
        cmp "$first_file" "$fosh" || fail 'Hash collision.'
    done

    printf 'identical'
    for fosh in $files_of_same_hash; do printf " %q" "$fosh"; done
    printf '\n'
done
