#! /bin/zsh

# Jonathan Frech, 2nd of June 2020

jt="$(realpath "$(dirname "$0")/../../jt")"
fonts_directory="$HOME/.local/share/fonts"

download_font () {
    url="$1" base_name="$2" extension="$3"
    [ ! "$extension" = 'zip' ] \
        && "$jt" internal fail "Unknown extension '$extension'."

    [ -e "$fonts_directory/$base_name" ] && "$jt" internal fail \
        "A font of the name '$base_name' appears to already be installed."
    mkdir -p "$fonts_directory/$base_name"

    curl --silent --fail "$url/$base_name.$extension" \
        > "$fonts_directory/$base_name/$base_name.$extension"
    unzip -d "$fonts_directory/$base_name" \
        "$fonts_directory/$base_name/$base_name.$extension" > /dev/null }

download_font 'https://rubjo.github.io/victor-mono' 'VictorMonoAll' 'zip'

fc-cache -f
